# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSHODock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddSHODock(object):
    def setupUi(self, AddSHODock):
        AddSHODock.setObjectName("AddSHODock")
        AddSHODock.resize(613, 403)
        AddSHODock.setMinimumSize(QtCore.QSize(358, 336))
        AddSHODock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.l_sho = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_sho.sizePolicy().hasHeightForWidth())
        self.l_sho.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l_sho.setFont(font)
        self.l_sho.setTextFormat(QtCore.Qt.AutoText)
        self.l_sho.setScaledContents(True)
        self.l_sho.setWordWrap(True)
        self.l_sho.setObjectName("l_sho")
        self.horizontalLayout_2.addWidget(self.l_sho)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_center = QtWidgets.QRadioButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_center.sizePolicy().hasHeightForWidth())
        self.rb_center.setSizePolicy(sizePolicy)
        self.rb_center.setChecked(True)
        self.rb_center.setObjectName("rb_center")
        self.verticalLayout.addWidget(self.rb_center)
        self.rb_left = QtWidgets.QRadioButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_left.sizePolicy().hasHeightForWidth())
        self.rb_left.setSizePolicy(sizePolicy)
        self.rb_left.setObjectName("rb_left")
        self.verticalLayout.addWidget(self.rb_left)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_vxmax = QtWidgets.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_vxmax.sizePolicy().hasHeightForWidth())
        self.le_vxmax.setSizePolicy(sizePolicy)
        self.le_vxmax.setObjectName("le_vxmax")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_vxmax)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pb_ok = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_ok.sizePolicy().hasHeightForWidth())
        self.pb_ok.setSizePolicy(sizePolicy)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_3.addWidget(self.pb_ok)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.te_addsho = QtWidgets.QTextEdit(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.te_addsho.setFont(font)
        self.te_addsho.setObjectName("te_addsho")
        self.horizontalLayout_4.addWidget(self.te_addsho)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        AddSHODock.setWidget(self.dockWidgetContents)

        self.retranslateUi(AddSHODock)
        QtCore.QMetaObject.connectSlotsByName(AddSHODock)

    def retranslateUi(self, AddSHODock):
        _translate = QtCore.QCoreApplication.translate
        AddSHODock.setWindowTitle(_translate("AddSHODock", "Add Simple Harmonic Oscillator Potential"))
        self.l_sho.setText(_translate("AddSHODock", "Add SHO Potential "))
        self.rb_center.setText(_translate("AddSHODock", "SHO Min at Well Center"))
        self.rb_left.setText(_translate("AddSHODock", "SHO Min at Left Edge"))
        self.label.setText(_translate("AddSHODock", "PE at Xmax (eV)"))
        self.le_vxmax.setText(_translate("AddSHODock", "40.0"))
        self.pb_ok.setText(_translate("AddSHODock", "Click to Add  Harmonic Oscillator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSHODock = QtWidgets.QDockWidget()
    ui = Ui_AddSHODock()
    ui.setupUi(AddSHODock)
    AddSHODock.show()
    sys.exit(app.exec_())

