# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddMultiBarriersDock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddMultiBarriersDock(object):
    def setupUi(self, AddMultiBarriersDock):
        AddMultiBarriersDock.setObjectName("AddMultiBarriersDock")
        AddMultiBarriersDock.resize(482, 413)
        AddMultiBarriersDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(13, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.testLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.testLabel.setObjectName("testLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.testLabel)
        self.le_numbarriers = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_numbarriers.setObjectName("le_numbarriers")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_numbarriers)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_barwidth = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_barwidth.setObjectName("le_barwidth")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_barwidth)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(13, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_width = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_width.setObjectName("le_width")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_width)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_barheight = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_barheight.setObjectName("le_barheight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_barheight)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pb_addbarriers = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pb_addbarriers.setObjectName("pb_addbarriers")
        self.horizontalLayout_5.addWidget(self.pb_addbarriers)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.te_multibarriers = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.te_multibarriers.setObjectName("te_multibarriers")
        self.verticalLayout.addWidget(self.te_multibarriers)
        AddMultiBarriersDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(AddMultiBarriersDock)
        QtCore.QMetaObject.connectSlotsByName(AddMultiBarriersDock)

    def retranslateUi(self, AddMultiBarriersDock):
        _translate = QtCore.QCoreApplication.translate
        AddMultiBarriersDock.setWindowTitle(_translate("AddMultiBarriersDock", "Add Multiple Barriers"))
        self.label.setText(_translate("AddMultiBarriersDock", "Add Multiple Barriers"))
        self.testLabel.setText(_translate("AddMultiBarriersDock", "Number of Barriers"))
        self.le_numbarriers.setText(_translate("AddMultiBarriersDock", "2"))
        self.label_3.setText(_translate("AddMultiBarriersDock", "Barrier Width (nm)"))
        self.le_barwidth.setText(_translate("AddMultiBarriersDock", "0.05"))
        self.label_2.setText(_translate("AddMultiBarriersDock", "SubWellWidth (nm)"))
        self.le_width.setText(_translate("AddMultiBarriersDock", "0.2"))
        self.label_4.setText(_translate("AddMultiBarriersDock", "and Height (eV)"))
        self.le_barheight.setText(_translate("AddMultiBarriersDock", "64.0"))
        self.pb_addbarriers.setText(_translate("AddMultiBarriersDock", "Click to Add Barriers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddMultiBarriersDock = QtWidgets.QDockWidget()
    ui = Ui_AddMultiBarriersDock()
    ui.setupUi(AddMultiBarriersDock)
    AddMultiBarriersDock.show()
    sys.exit(app.exec_())

