# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSlopedPotentialDock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddSlopedPotentialDock(object):
    def setupUi(self, AddSlopedPotentialDock):
        AddSlopedPotentialDock.setObjectName("AddSlopedPotentialDock")
        AddSlopedPotentialDock.resize(549, 424)
        AddSlopedPotentialDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_xmin = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_xmin.setObjectName("le_xmin")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_xmin)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_xmax = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_xmax.setObjectName("le_xmax")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_xmax)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_vxmin = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_vxmin.setObjectName("le_vxmin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_vxmin)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_vxmax = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_vxmax.setObjectName("le_vxmax")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_vxmax)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pb_ok = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout.addWidget(self.pb_ok)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.te_addslope = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.te_addslope.setObjectName("te_addslope")
        self.verticalLayout.addWidget(self.te_addslope)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        AddSlopedPotentialDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(AddSlopedPotentialDock)
        QtCore.QMetaObject.connectSlotsByName(AddSlopedPotentialDock)

    def retranslateUi(self, AddSlopedPotentialDock):
        _translate = QtCore.QCoreApplication.translate
        AddSlopedPotentialDock.setWindowTitle(_translate("AddSlopedPotentialDock", "Add Linear Potential"))
        self.label_6.setText(_translate("AddSlopedPotentialDock", "Add Linear Potential"))
        self.label_2.setText(_translate("AddSlopedPotentialDock", "Xmin (nm)"))
        self.le_xmin.setText(_translate("AddSlopedPotentialDock", "0.0"))
        self.label_4.setText(_translate("AddSlopedPotentialDock", "Xmax (nm)"))
        self.le_xmax.setText(_translate("AddSlopedPotentialDock", "0.40"))
        self.label.setText(_translate("AddSlopedPotentialDock", "PE at Xmin (eV)"))
        self.le_vxmin.setText(_translate("AddSlopedPotentialDock", "0.0"))
        self.label_5.setText(_translate("AddSlopedPotentialDock", "PE at Xmax (eV"))
        self.le_vxmax.setText(_translate("AddSlopedPotentialDock", "40.0"))
        self.pb_ok.setText(_translate("AddSlopedPotentialDock", "Click to Add Potential"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSlopedPotentialDock = QtWidgets.QDockWidget()
    ui = Ui_AddSlopedPotentialDock()
    ui.setupUi(AddSlopedPotentialDock)
    AddSlopedPotentialDock.show()
    sys.exit(app.exec_())

