# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BuildWellDock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BuildWellDock(object):
    def setupUi(self, BuildWellDock):
        BuildWellDock.setObjectName("BuildWellDock")
        BuildWellDock.resize(396, 439)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BuildWellDock.sizePolicy().hasHeightForWidth())
        BuildWellDock.setSizePolicy(sizePolicy)
        BuildWellDock.setMinimumSize(QtCore.QSize(62, 311))
        BuildWellDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(10, 0))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_width = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_width.setObjectName("le_width")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_width)
        self.le_heightleft = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_heightleft.setObjectName("le_heightleft")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_heightleft)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_heightright = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_heightright.setObjectName("le_heightright")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_heightright)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pb_ok = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_ok.sizePolicy().hasHeightForWidth())
        self.pb_ok.setSizePolicy(sizePolicy)
        self.pb_ok.setAutoDefault(True)
        self.pb_ok.setFlat(False)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_2.addWidget(self.pb_ok)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.te_message = QtWidgets.QTextEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_message.sizePolicy().hasHeightForWidth())
        self.te_message.setSizePolicy(sizePolicy)
        self.te_message.setMinimumSize(QtCore.QSize(0, 0))
        self.te_message.setObjectName("te_message")
        self.verticalLayout.addWidget(self.te_message)
        BuildWellDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(BuildWellDock)
        QtCore.QMetaObject.connectSlotsByName(BuildWellDock)

    def retranslateUi(self, BuildWellDock):
        _translate = QtCore.QCoreApplication.translate
        BuildWellDock.setWindowTitle(_translate("BuildWellDock", "BuildWell"))
        self.label.setText(_translate("BuildWellDock", "Set Well Width and Heights"))
        self.label_2.setText(_translate("BuildWellDock", "Total Width (nm)"))
        self.le_width.setText(_translate("BuildWellDock", "0.40"))
        self.le_heightleft.setText(_translate("BuildWellDock", "inf"))
        self.label_4.setText(_translate("BuildWellDock", "PE at Right Edge (eV)"))
        self.le_heightright.setText(_translate("BuildWellDock", "64.0"))
        self.label_3.setText(_translate("BuildWellDock", "PE at Left Edge (eV)"))
        self.pb_ok.setText(_translate("BuildWellDock", "Click to Build Well"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BuildWellDock = QtWidgets.QDockWidget()
    ui = Ui_BuildWellDock()
    ui.setupUi(BuildWellDock)
    BuildWellDock.show()
    sys.exit(app.exec_())

