# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindStatesWellDock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FindStatesWellDock(object):
    def setupUi(self, FindStatesWellDock):
        FindStatesWellDock.setObjectName("FindStatesWellDock")
        FindStatesWellDock.resize(434, 525)
        FindStatesWellDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        FindStatesWellDock.setWindowTitle("")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_numx = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_numx.setObjectName("le_numx")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_numx)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_emin = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_emin.setObjectName("le_emin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_emin)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_emax = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_emax.setObjectName("le_emax")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_emax)
        self.le_dele = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_dele.setObjectName("le_dele")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_dele)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.cb_figure = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.cb_figure.setObjectName("cb_figure")
        self.horizontalLayout_3.addWidget(self.cb_figure)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pb_findstates = QtWidgets.QPushButton(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_findstates.setFont(font)
        self.pb_findstates.setObjectName("pb_findstates")
        self.horizontalLayout_3.addWidget(self.pb_findstates)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.proBar = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.proBar.setProperty("value", 24)
        self.proBar.setObjectName("proBar")
        self.verticalLayout.addWidget(self.proBar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_statenum = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.le_statenum.setObjectName("le_statenum")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_statenum)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.pb_plotpsi = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_plotpsi.sizePolicy().hasHeightForWidth())
        self.pb_plotpsi.setSizePolicy(sizePolicy)
        self.pb_plotpsi.setObjectName("pb_plotpsi")
        self.horizontalLayout_4.addWidget(self.pb_plotpsi)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pb_savepsi = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_savepsi.sizePolicy().hasHeightForWidth())
        self.pb_savepsi.setSizePolicy(sizePolicy)
        self.pb_savepsi.setObjectName("pb_savepsi")
        self.horizontalLayout_4.addWidget(self.pb_savepsi)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.te_findstates = QtWidgets.QTextEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_findstates.sizePolicy().hasHeightForWidth())
        self.te_findstates.setSizePolicy(sizePolicy)
        self.te_findstates.setObjectName("te_findstates")
        self.verticalLayout.addWidget(self.te_findstates)
        FindStatesWellDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(FindStatesWellDock)
        QtCore.QMetaObject.connectSlotsByName(FindStatesWellDock)

    def retranslateUi(self, FindStatesWellDock):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("FindStatesWellDock", "Find Stationary States"))
        self.label_2.setText(_translate("FindStatesWellDock", "Num X bins"))
        self.le_numx.setText(_translate("FindStatesWellDock", "500"))
        self.label_4.setText(_translate("FindStatesWellDock", "Min E (eV)"))
        self.le_emin.setText(_translate("FindStatesWellDock", "1.0"))
        self.label_3.setText(_translate("FindStatesWellDock", "Delta E (eV)"))
        self.label_5.setText(_translate("FindStatesWellDock", "Max E (eV)"))
        self.le_emax.setText(_translate("FindStatesWellDock", "64.0"))
        self.le_dele.setText(_translate("FindStatesWellDock", "0.1"))
        self.cb_figure.setText(_translate("FindStatesWellDock", "Show Graph"))
        self.pb_findstates.setText(_translate("FindStatesWellDock", "Click to Find States"))
        self.label_6.setText(_translate("FindStatesWellDock", "State ID"))
        self.le_statenum.setText(_translate("FindStatesWellDock", "1"))
        self.pb_plotpsi.setText(_translate("FindStatesWellDock", "Plot Psi"))
        self.pb_savepsi.setText(_translate("FindStatesWellDock", "Save Psi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindStatesWellDock = QtWidgets.QDockWidget()
    ui = Ui_FindStatesWellDock()
    ui.setupUi(FindStatesWellDock)
    FindStatesWellDock.show()
    sys.exit(app.exec_())

